# coding: utf-8

"""
    Togai Apis

    APIs for Togai App

    The version of the OpenAPI document: 1.0
    Contact: engg@togai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MigrationMode(str, Enum):
    """
    MigrationMode
    """

    """
    allowed enum values
    """
    IMMEDIATE = 'IMMEDIATE'
    IMMEDIATE_IGNORE_OVERRIDE = 'IMMEDIATE_IGNORE_OVERRIDE'
    NEXT_CYCLE = 'NEXT_CYCLE'
    NEXT_CYCLE_IGNORE_OVERRIDE = 'NEXT_CYCLE_IGNORE_OVERRIDE'
    NONE = 'NONE'
    START_OF_CURRENT_CYCLE = 'START_OF_CURRENT_CYCLE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MigrationMode from a JSON string"""
        return cls(json.loads(json_str))


