# coding: utf-8

"""
    Togai Apis

    APIs for Togai App

    The version of the OpenAPI document: 1.0
    Contact: engg@togai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PurchaseType(str, Enum):
    """
    Specifies whether this purchase is for granting entitlements or for an association or for wallet topup or prepaid purchase. If left null, ENTITLEMENT_GRANT is taken as default
    """

    """
    allowed enum values
    """
    ENTITLEMENT_GRANT = 'ENTITLEMENT_GRANT'
    ASSOCIATION = 'ASSOCIATION'
    WALLET_TOPUP = 'WALLET_TOPUP'
    PREPAID = 'PREPAID'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PurchaseType from a JSON string"""
        return cls(json.loads(json_str))


