# coding: utf-8

"""
    Togai Apis

    APIs for Togai App

    The version of the OpenAPI document: 1.0
    Contact: engg@togai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UsageMeterAggregation(str, Enum):
    """
    Aggregation to be applied on usage meter result * COUNT - Counts number of events matching the usage meter * SUM - Sums up results of computation of all events matching usage meter 
    """

    """
    allowed enum values
    """
    COUNT = 'COUNT'
    SUM = 'SUM'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UsageMeterAggregation from a JSON string"""
        return cls(json.loads(json_str))


